<?php if ($this->pageCount): ?>
    <div class="pagination-control">
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <a href="<?php echo $this->baseUrl('users') . '?page=' . $this->previous; ?>">
                Previous
            </a> |
        <?php else: ?>
            <span class="disabled">&lt; Previous</span> |
        <?php endif; ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <a href="<?php echo $this->baseUrl('users') . '?page=' . $this->next; ?>">
                Next &gt;
            </a>
        <?php else: ?>
            <span class="disabled">Next &gt;</span>
        <?php endif; ?>
        <span class="pagecount">
            Page <?php echo $this->current; ?> of <?php echo $this->pageCount; ?>
        </span>
    </div>
<?php endif; ?>