<?php
/**
 * Header artial
 * 
 * @category Layout
 * @author Santosh Moktan <itmyprofession@gmail.com>
 * @copyright (c) 
 * @license 
 * @version 1
 */
?>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar">
        <div class="navbar-inner">
            <div class="container">
                <a class="brand" href="<?php echo $this->baseUrl() ?>">ZF1 App</a>
                <ul class="nav">
                    <li><a href="<?php echo $this->baseurl('users'); ?>">Users</a></li>
                    <li><a href="<?php echo $this->baseurl('register'); ?>">User Registration</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>  