<?php
/**
 * Layout
 * 
 * @category Layout
 * @author Santosh Moktan <itmyprofession@gmail.com>
 * @copyright (c) 
 * @license 
 * @version 1
 */
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta name="robots" content="index, follow" />
            <link rel="stylesheet" type="text/css" href="../assets/css/bootstrap.css" />
            <link rel="stylesheet" type="text/css" href="../assets/css/styles.css" />
            <script type="text/javascript" src="../assets/js/jquery/jquery.min.js"></script>
            <script type="text/javascript" src="../assets/js/bootstrap.js"></script>
            <?php echo $this->headMeta(); ?>
            <?php echo $this->headTitle(); ?>
            <?php echo $this->headScript(); ?>
            <?php echo $this->headLink(); ?>
    </head>
    <body>
        <?php echo $this->render('_header.phtml'); ?>
        <div class="container">
            <?php echo $this->layout()->content; ?>
            <hr/>
            <?php echo $this->render('_footer.phtml'); ?>
        </div>
    </body>
</html>
